apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agile-sim-data
  namespace: agile-sim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: ""   # set to your cluster's storage class if not using the default
